title: Shader Tips
description: A link site of all the various useful shader sites and information that I have stumbled on over time.
theme: just-the-docs

url: https://shader.tips

aux_links:
  Contribute Knowledge:
    - https://github.com/ZekkVRC/shader.tips

FirstPartyAuthorLink: "https://links.zekk.dev"

color_scheme: dark

logo: /assets/LogoLo4800.gif
favicon_ico: /assets/LogoLo4800.gif

enable_copy_code_button: true

callouts:
  Warning:
    title: Warning
    color: red
  Caution:
    title: Caution
    color: yellow
  WIP:
    title: WIP
    color: yellow
  VRChat:
    title: VRChat Specific Technique
    color: blue
  ThirdPartyLicense:
    title: Third Party License
    color: red